name: 'cpp/header-only'

on:
  push:
    branches:
    - main

jobs:
  publish:
    name: 'Publish to cpp/header-only'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        ref: main

    - uses: JamesIves/github-pages-deploy-action@v4.7.4
      with:
        branch: cpp/header-only
        folder: ${{github.workspace}}/cpp/src/
